//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saver_Images_from_OmSTU_Lib.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Saver_Images_from_OmSTU_Lib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Book saved.
        /// </summary>
        internal static string Form1_buttonSave_Click_Book_saved {
            get {
                return ResourceManager.GetString("Form1_buttonSave_Click_Book_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Empty path.
        /// </summary>
        internal static string Form1_buttonSave_Click_Empty_path {
            get {
                return ResourceManager.GetString("Form1_buttonSave_Click_Empty_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Empty URL.
        /// </summary>
        internal static string Form1_buttonSave_Click_Empty_URL {
            get {
                return ResourceManager.GetString("Form1_buttonSave_Click_Empty_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error page number.
        /// </summary>
        internal static string Form1_buttonSave_Click_Error_page_number {
            get {
                return ResourceManager.GetString("Form1_buttonSave_Click_Error_page_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter path and try again.
        /// </summary>
        internal static string Form1_buttonSave_Click_Please_enter_path_and_try_again {
            get {
                return ResourceManager.GetString("Form1_buttonSave_Click_Please_enter_path_and_try_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter the URL and try again.
        /// </summary>
        internal static string Form1_buttonSave_Click_Please_enter_the_URL_and_try_again {
            get {
                return ResourceManager.GetString("Form1_buttonSave_Click_Please_enter_the_URL_and_try_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start page should be less than or equal to end page.
        /// </summary>
        internal static string Form1_buttonSave_Click_Start_page_should_be_less_than_or_equal_to_end_page {
            get {
                return ResourceManager.GetString("Form1_buttonSave_Click_Start_page_should_be_less_than_or_equal_to_end_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The book was saved in the path: .
        /// </summary>
        internal static string Form1_buttonSave_Click_The_book_was_saved_in_the_path__ {
            get {
                return ResourceManager.GetString("Form1_buttonSave_Click_The_book_was_saved_in_the_path__", resourceCulture);
            }
        }
    }
}
